type and rem_vertices! fixed
PIK-ICoNe/EmbeddedGraphs.jl pull request #25
Opened 2022-04-12 18:16 UTC by acejolanda

2022-04-13 06:42 UTC, lindnemi requested changes
Looks quite good already! I noticed two minor things, as soon as they're adressed this PR can be merged

2022-04-13 06:42 UTC, lindnemi commented on src/lightgraph_extensions.jl
> +    vs_sorted = sort(vs, rev=true)
we should use the mutating `sort!` here, instead of allocating a new array `vs_sorted`

2022-04-13 06:42 UTC, lindnemi commented on test/runtests.jl
> +    #@test typeof(zero(eg)) <:  AbstractEmbeddedGraph
is there a problem with this test?

2022-04-19 16:47 UTC, acejolanda commented
the two minor things (sort! and the test of the zero(eg) function) are fixed now :)

2022-04-19 16:57 UTC, acejolanda commented
the function rem_vertices! and the function zero(eg) are fixed now :)

2022-04-20 07:28 UTC, lindnemi approved these changes
I changed sort! back to `sort` again. Sorry. It's not obvious that we are mutating the input array `vs` and we can not know if the user wants to do something else with it

2022-04-20 07:33 UTC, merged